# python demo/test_net_on_wsi_monuseg.py --model_id '0'
# python demo/test_net_on_wsi_monuseg.py --model_id '1'
python demo/test_net_on_wsi_monuseg.py --model_id '2'
# python demo/test_net_on_wsi_monuseg.py --model_id '3'
# python demo/test_net_on_wsi_monuseg.py --model_id '4'
# python demo/test_net_on_wsi_monuseg.py --model_id '5'
# python demo/test_net_on_wsi_monuseg.py --model_id '6'
# python demo/test_net_on_wsi_monuseg.py --model_id '7'
python demo/test_net_on_wsi_monuseg.py --model_id '8'
python demo/test_net_on_wsi_monuseg.py --model_id '14'