### 0 1 2 3 4 6 9 11 14 for graph
# python demo/test_net_on_nr.py --model_id '0'
# python demo/test_net_on_nr.py --model_id '1'
# python demo/test_net_on_nr.py --model_id '2'
# python demo/test_net_on_nr.py --model_id '3'
# python demo/test_net_on_nr.py --model_id '4'
# python demo/test_net_on_nr.py --model_id '5'
python demo/test_net_on_nr.py --model_id '6'
# python demo/test_net_on_nr.py --model_id '7'
# python demo/test_net_on_nr.py --model_id '8'
# python demo/test_net_on_nr.py --model_id '9'
# python demo/test_net_on_nr.py --model_id '10'
# python demo/test_net_on_nr.py --model_id '11'
# python demo/test_net_on_nr.py --model_id '12'
# python demo/test_net_on_nr.py --model_id '13'
# python demo/test_net_on_nr.py --model_id '14'