MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN_ONLY: False
  RPN:
    # options:
    # EmbeddingConvRPNHead
    # SingleConvRPNHead
    RPN_HEAD: "EmbeddingConvRPNHead"
    RPN_EMBED_DIM: 12
    # options: {1: contrastive loss, 2: triplet loss}
    RPN_EMBED_LOSS: 1
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    # dim of embedding before cls
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    # choice:
    # "FastRCNNPredictor"
    # "FPNPredictor"
    PREDICTOR: "FPNPredictor"
    LOSS_MODE: 0 # {0: no embed, 1: pair loss, 2: triplet loss}
DATASETS:
  TRAIN: ("moNuSeg_600_train", )
  VAL: ("moNuSeg_600_val",)
  TEST: ("moNuSeg_600_val",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 600
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 600
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Assume 4 gpus
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (5000, 10000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2500
  MAX_EPOCH: 20
  IMS_PER_BATCH: 12
OUTPUT_DIR: "/mnt/DATA_OTHER/moNuSeg/results"
# OUTPUT_FOLDER: "rc_faster_rcnn_R_50_FPN_1x"
# OUTPUT_FOLDER: "rc_faster_rcnn_R_50_FPN_1x_roi_triplet"
OUTPUT_FOLDER: "rc_faster_rcnn_R_50_FPN_1x_rpn_pair"
# OUTPUT_FOLDER: "rc_faster_rcnn_R_50_FPN_1x_rpn_only"
# OUTPUT_FOLDER: "rc_faster_rcnn_R_50_FPN_1x_triplet_rpn_only"
# OUTPUT_FOLDER: "rc_faster_rcnn_R_50_FPN_1x_siamese"