MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  RPN_ONLY: True
  RETINANET_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    POSITIVE_FRACTION: 0.2
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  RETINANET:
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: -1
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    EMBED_ON: True
    EMBED_LOSS: 1
    EMBED_DIM: 20
DATASETS:
  TRAIN: ("moNuSeg_600_train", )
  VAL: ("moNuSeg_600_val",)
  TEST: ("moNuSeg_600_train",)
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MAX_SIZE_TRAIN: 600
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 600
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Assume 4 gpus
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (5000, 10000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2500
  MAX_EPOCH: 20
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "/mnt/DATA_OTHER/moNuSeg/results"
# OUTPUT_FOLDER: "rc_retinanet_X_101_32x8d_FPN_1x"
OUTPUT_FOLDER: "rc_retinanet_X_101_32x8d_FPN_1x_pair"
